### ISSUE TITLE
Text is always empty

### ISSUE THREAD

**Issue by Tiagoperes** [AlexanderPrendota/kotlin-compiler-server#247]
I'm probably doing something wrong, can anybody help me please?

I'm trying to run a simple code, but the service always outputs a JSON where `text` is an empty string.

To test it further, I used a web page with the kotlin playground lib. If I use the default option for `server`, everything works fine: `text` comes with the expected output. But, as soon as I change `server` to the address of the local instance I'm running, things stop working, because `text` is empty no matter the input.

This is the code sample I'm trying to run:
```kotlin
fun main() {
    println("test")
}
```

When using the online version of kotlin-compiler-server, the service responds with:

```json
{
  "errors":{
    "File.kt":[]
  },
  "exception":null,
  "text":"<outStream>test\n</outStream>"
}
```

When using my local version where the single modification is the port the application runs at, , the service responds with:
```json
{
  "errors":{
    "File.kt":[]
  },
  "exception":null,
  "text":""
}
```

Thanks in advance for any help.

**Comment by Tiagoperes** [comment]
I just checked in my Mac, it works. This problem only happens in my Windows machine. Could there be any additional step to make it work on Windows?

**Comment by wayfarer-rus** [comment]
Yep! Your right!

Issue caused by specific character difference for java runtime.

I've created MR with the fix for it https://github.com/AlexanderPrendota/kotlin-compiler-server/pull/248

**Comment by AlexanderPrendota** [comment]
I like open source community <3
